from __future__ import annotations

INVESTOR_INTENT_CONTRACT_VERSION_V1 = 'ADVISORY_INVESTOR_INTENT_CONTRACT_V1'
POLICY_CONTRACT_VERSION_V1 = 'ADVISORY_POLICY_CONTRACT_V1'
ASSUMPTION_MANIFEST_CONTRACT_VERSION_V1 = 'ADVISORY_ASSUMPTION_MANIFEST_CONTRACT_V1'
HOUSEHOLD_SNAPSHOT_CONTRACT_VERSION_V1 = 'ADVISORY_HOUSEHOLD_SNAPSHOT_CONTRACT_V1'
SNAPSHOT_VALIDATION_DECISION_CONTRACT_VERSION_V1 = 'ADVISORY_SNAPSHOT_VALIDATION_DECISION_CONTRACT_V1'
SNAPSHOT_RUN_ENVELOPE_CONTRACT_VERSION_V1 = 'ADVISORY_SNAPSHOT_RUN_ENVELOPE_CONTRACT_V1'
PORTFOLIO_INTENT_CONTRACT_VERSION_V1 = 'ADVISORY_PORTFOLIO_INTENT_CONTRACT_V1'
PROMOTION_DECISION_CONTRACT_VERSION_V1 = 'ADVISORY_PROMOTION_DECISION_CONTRACT_V1'
EXECUTION_INTENT_CONTRACT_VERSION_V1 = 'ADVISORY_EXECUTION_INTENT_CONTRACT_V1'
KERNEL_RUN_ENVELOPE_CONTRACT_VERSION_V1 = 'ADVISORY_KERNEL_RUN_ENVELOPE_CONTRACT_V1'
INVESTOR_INTENT_NORMALIZER_VERSION_V1 = 'investor_intent_normalizer_v1'
POLICY_COMPILER_ACTOR_PREFIX_V1 = 'policy_compiler'
HOUSEHOLD_SNAPSHOT_BUILDER_VERSION_V1 = 'household_snapshot_builder_v1'
SNAPSHOT_VALIDATION_DECISION_VERSION_V1 = 'snapshot_validation_decision_v1'
SNAPSHOT_RUN_ENVELOPE_VERSION_V1 = 'snapshot_run_envelope_v1'
PORTFOLIO_INTENT_BUILDER_VERSION_V1 = 'portfolio_intent_builder_v1'
PROMOTION_DECISION_EVALUATOR_VERSION_V1 = 'promotion_decision_evaluator_v1'
EXECUTION_INTENT_BUILDER_VERSION_V1 = 'execution_intent_builder_v1'
KERNEL_RUN_ENVELOPE_VERSION_V1 = 'kernel_run_envelope_v1'
ASSUMPTION_MANIFEST_STATUSES_V1 = {
    'ACTIVE',
    'SUPERSEDED',
    'INVALID_HARD_STOP',
}
ASSUMPTION_MANIFEST_TYPES_V1 = {
    'policy_rule_interpretation',
}

INVESTOR_INTENT_COMPLETENESS_STATUSES_V1 = {
    'COMPLETE',
    'INCOMPLETE_REMEDIABLE',
    'INVALID_HARD_STOP',
}

POLICY_COMPLETENESS_STATUSES_V1 = {
    'VALID',
    'INVALID_REMEDIABLE',
    'INVALID_HARD_STOP',
}

ADVISORY_VALIDITY_TIERS_V1 = {
    'VALID_EXECUTION_ELIGIBLE',
    'VALID_ADVISORY_ONLY',
    'INVALID_REMEDIABLE',
    'INVALID_HARD_STOP',
}

SNAPSHOT_VALIDATION_OUTCOMES_V1 = {
    'valid',
    'blocked',
}

PORTFOLIO_INTENT_EXECUTION_ELIGIBILITY_V1 = {
    'EXECUTION_ELIGIBLE',
    'ADVISORY_ONLY',
    'BLOCKED',
}

POLICY_ALLOCATION_MODES_V1 = {
    'EXIT_ONLY',
    'TARGET_WEIGHTS',
}

VALUE_BASIS_STATUSES_V1 = {
    'VALID',
    'BLOCKED',
}

VALUE_BASIS_COMPLETENESS_STATUSES_V1 = {
    'COMPLETE',
    'INCOMPLETE',
}

VALUE_BASIS_FRESHNESS_STATUSES_V1 = {
    'CURRENT',
    'STALE',
    'UNKNOWN',
}

VALUE_BASIS_VALUATION_MODES_V1 = {
    'UNAVAILABLE',
    'GOVERNED_EQUITY_MARKS_WITH_VERIFIED_CASH_V1',
}

ALLOCATION_ADVISORY_STATUSES_V1 = {
    'DISABLED',
    'BLOCKED',
    'READY',
}

PROMOTION_DECISION_OUTCOMES_V1 = {
    'promote',
    'no_action',
    'blocked',
}

PROMOTION_RECORD_V2_STATUSES_V1 = {
    'AUTHORIZED',
    'NO_ACTION',
    'BLOCKED',
    'SUPERSEDED',
}

OPERATING_MODES_V1 = {
    'advisory_only',
    'manual_execution_only',
    'automation_allowed',
}

TIME_HORIZONS_V1 = {
    'short_term',
    'medium_term',
    'long_term',
}

RISK_PREFERENCES_V1 = {
    'conservative',
    'balanced',
    'growth',
}

LIQUIDITY_REQUIREMENTS_V1 = {
    'low',
    'moderate',
    'high',
}

CONCENTRATION_PREFERENCES_V1 = {
    'diversified',
    'moderate',
    'concentrated',
}

AUTOMATION_PREFERENCES_V1 = {
    'manual_only',
    'proposal_only',
    'auto_with_approval',
}

APPROVAL_PREFERENCES_V1 = {
    'explicit_approval_required',
    'delegate_allowed',
}
