from __future__ import annotations

import sys
from pathlib import Path

SOURCE_ROOT = Path("/home/node/constellation")
if str(SOURCE_ROOT) not in sys.path:
    sys.path.insert(0, str(SOURCE_ROOT))

from constellation_2.common.paper_session_ledger_v1 import build_paper_session_ledger_v1  # noqa: E402


def test_paper_session_ledger_persists_constitutional_context() -> None:
    ledger = build_paper_session_ledger_v1(
        day_utc="2026-04-16",
        session_id="paper_session:2026-04-16:PAPER",
        evaluated_at_utc="2026-04-16T00:00:00Z",
        provenance={"repo": "constellation", "module": "test", "git_sha": "a" * 40},
        fact_refs=[
            {
                "logical_name": "a",
                "required_for_authority": True,
                "absolute_path": "/tmp/a.json",
                "schema_id": "a",
                "schema_version": "v1",
                "producer": {"repo": "constellation", "module": "test", "git_sha": "a" * 40},
                "artifact_timestamp_utc": "2026-04-16T00:00:00Z",
                "artifact_day_utc": "2026-04-16",
                "artifact_session_id": "paper_session:2026-04-16:PAPER",
                "content_hash": "1" * 64,
                "presence_verdict": "PRESENT",
                "schema_verdict": "VALID",
                "linkage_verdict": "LINKED",
                "freshness_verdict": "CURRENT",
                "duplicate_resolution_verdict": "SINGLE_CANONICAL_PATH",
                "blocking_codes": [],
                "lookup_evidence": ["ok"],
                "fact_snapshot": {},
            },
            {
                "logical_name": "b",
                "required_for_authority": True,
                "absolute_path": "/tmp/b.json",
                "schema_id": "b",
                "schema_version": "v1",
                "producer": {"repo": "constellation", "module": "test", "git_sha": "a" * 40},
                "artifact_timestamp_utc": "2026-04-16T00:00:00Z",
                "artifact_day_utc": "2026-04-16",
                "artifact_session_id": "paper_session:2026-04-16:PAPER",
                "content_hash": "2" * 64,
                "presence_verdict": "PRESENT",
                "schema_verdict": "VALID",
                "linkage_verdict": "LINKED",
                "freshness_verdict": "CURRENT",
                "duplicate_resolution_verdict": "SINGLE_CANONICAL_PATH",
                "blocking_codes": [],
                "lookup_evidence": ["ok"],
                "fact_snapshot": {},
            },
            {
                "logical_name": "c",
                "required_for_authority": True,
                "absolute_path": "/tmp/c.json",
                "schema_id": "c",
                "schema_version": "v1",
                "producer": {"repo": "constellation", "module": "test", "git_sha": "a" * 40},
                "artifact_timestamp_utc": "2026-04-16T00:00:00Z",
                "artifact_day_utc": "2026-04-16",
                "artifact_session_id": "paper_session:2026-04-16:PAPER",
                "content_hash": "3" * 64,
                "presence_verdict": "PRESENT",
                "schema_verdict": "VALID",
                "linkage_verdict": "LINKED",
                "freshness_verdict": "CURRENT",
                "duplicate_resolution_verdict": "SINGLE_CANONICAL_PATH",
                "blocking_codes": [],
                "lookup_evidence": ["ok"],
                "fact_snapshot": {},
            },
            {
                "logical_name": "d",
                "required_for_authority": True,
                "absolute_path": "/tmp/d.json",
                "schema_id": "d",
                "schema_version": "v1",
                "producer": {"repo": "constellation", "module": "test", "git_sha": "a" * 40},
                "artifact_timestamp_utc": "2026-04-16T00:00:00Z",
                "artifact_day_utc": "2026-04-16",
                "artifact_session_id": "paper_session:2026-04-16:PAPER",
                "content_hash": "4" * 64,
                "presence_verdict": "PRESENT",
                "schema_verdict": "VALID",
                "linkage_verdict": "LINKED",
                "freshness_verdict": "CURRENT",
                "duplicate_resolution_verdict": "SINGLE_CANONICAL_PATH",
                "blocking_codes": [],
                "lookup_evidence": ["ok"],
                "fact_snapshot": {},
            },
        ],
        evidence_freeze={
            "evidence_digest": "f" * 64,
            "overall_evidence_status": "READY",
            "blocking_codes": [],
            "inputs": [
                {
                    "logical_name": "a",
                    "required_for_authority": True,
                    "absolute_path": "/tmp/a.json",
                    "schema_id": "a",
                    "schema_version": "v1",
                    "producer": {"repo": "constellation", "module": "test", "git_sha": "a" * 40},
                    "artifact_timestamp_utc": "2026-04-16T00:00:00Z",
                    "artifact_day_utc": "2026-04-16",
                    "artifact_session_id": "paper_session:2026-04-16:PAPER",
                    "content_hash": "1" * 64,
                    "presence_verdict": "PRESENT",
                    "schema_verdict": "VALID",
                    "linkage_verdict": "LINKED",
                    "freshness_verdict": "CURRENT",
                    "duplicate_resolution_verdict": "SINGLE_CANONICAL_PATH",
                    "blocking_codes": [],
                    "lookup_evidence": ["ok"],
                    "fact_snapshot": {},
                },
                {
                    "logical_name": "b",
                    "required_for_authority": True,
                    "absolute_path": "/tmp/b.json",
                    "schema_id": "b",
                    "schema_version": "v1",
                    "producer": {"repo": "constellation", "module": "test", "git_sha": "a" * 40},
                    "artifact_timestamp_utc": "2026-04-16T00:00:00Z",
                    "artifact_day_utc": "2026-04-16",
                    "artifact_session_id": "paper_session:2026-04-16:PAPER",
                    "content_hash": "2" * 64,
                    "presence_verdict": "PRESENT",
                    "schema_verdict": "VALID",
                    "linkage_verdict": "LINKED",
                    "freshness_verdict": "CURRENT",
                    "duplicate_resolution_verdict": "SINGLE_CANONICAL_PATH",
                    "blocking_codes": [],
                    "lookup_evidence": ["ok"],
                    "fact_snapshot": {},
                },
                {
                    "logical_name": "c",
                    "required_for_authority": True,
                    "absolute_path": "/tmp/c.json",
                    "schema_id": "c",
                    "schema_version": "v1",
                    "producer": {"repo": "constellation", "module": "test", "git_sha": "a" * 40},
                    "artifact_timestamp_utc": "2026-04-16T00:00:00Z",
                    "artifact_day_utc": "2026-04-16",
                    "artifact_session_id": "paper_session:2026-04-16:PAPER",
                    "content_hash": "3" * 64,
                    "presence_verdict": "PRESENT",
                    "schema_verdict": "VALID",
                    "linkage_verdict": "LINKED",
                    "freshness_verdict": "CURRENT",
                    "duplicate_resolution_verdict": "SINGLE_CANONICAL_PATH",
                    "blocking_codes": [],
                    "lookup_evidence": ["ok"],
                    "fact_snapshot": {},
                },
            ],
        },
        authority_status="GRANTED",
        system_ready=True,
        submission_authorized=True,
        control_blocking_codes=[],
        submit_lifecycle={
            "submit_attempt_status": "SKIPPED",
            "submit_attempted": False,
            "submit_result_status": "NOT_OBSERVED",
            "reason_codes": [],
            "submit_evidence_refs": [],
            "finalization_status": "OPEN",
        },
        post_submit_lifecycle={
            "lineage_status": "NOT_OBSERVED_AT_EVALUATION",
            "latest_authoritative_lineage_ref": "",
            "latest_authoritative_lineage_sha256": "",
            "execution_evidence_refs": [],
            "reconciliation_refs": [],
            "gap_codes": [],
        },
        operator_summary={
            "authority_scope": "DERIVED_ONLY_VIEW",
            "ledger_ref": "/tmp/ledger.json",
            "summary_state": "AUTHORIZED_TO_PROCEED",
            "authority_status": "GRANTED",
            "submission_authorized": True,
            "non_authority_notice": "test",
            "blocking_codes": [],
        },
        constitutional_context={
            "proposal_hash": "1" * 64,
            "fact_bundle_hash": "2" * 64,
            "decision_enum": "REQUIRE_HUMAN_REVIEW",
            "effective_scope": {
                "global": "PAPER",
                "domain": "TRADING",
                "account": "DU1234567",
                "sleeve": "PRIMARY",
                "action_class": "CONSTRUCTIVE",
                "effective_authority": "REQUIRE_HUMAN_REVIEW",
            },
            "blocker_rules": ["RULE_A"],
            "rule_provenance": [
                {"rule_id": "rule_a", "gate_index": 5, "outcome": "FAIL", "detail": "detail"}
            ],
            "negative_evidence": [
                {
                    "type": "MISSING_FACT",
                    "fact": "policy_binding_fact",
                    "severity": "BLOCKING",
                    "detail": "required fact type missing: policy_binding_fact",
                }
            ],
            "policy_version": "constitutional_shadow_v1",
        },
    )
    payload = ledger.to_dict()
    assert payload["constitutional_context"]["decision_enum"] == "REQUIRE_HUMAN_REVIEW"
    assert payload["constitutional_context"]["effective_scope"]["effective_authority"] == "REQUIRE_HUMAN_REVIEW"
    assert payload["constitutional_context"]["negative_evidence"][0]["type"] == "MISSING_FACT"
