from __future__ import annotations

import copy
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from ops.aegis.operator_command_v1 import (
    active_opportunity_projection_v1,
    build_operator_state_snapshot_v1,
    validate_operator_state_snapshot_v1,
)


def _supported_candidate() -> dict[str, object]:
    return {
        "candidate_id": "cand-spy-long",
        "symbol": "SPY",
        "direction": "LONG",
        "sleeve_id": "C2_CROSS_ASSET_TREND_V1",
        "review_state": "review_required",
        "decision_support_brief": {
            "candidate_id": "cand-spy-long",
            "direct_answer": "Manual capture may be reasonable after review.",
            "trust_classification": "partially_supported",
            "trust_score_label": "Partial support",
            "decision_guidance": "reasonable_for_manual_review",
            "why_triggered": "SPY long was generated by the sleeve trigger.",
            "historical_support": [{"item": "event study", "status": "present"}],
            "weakening_factors": [],
            "sleeve_health_context": {"overall_health": "watch"},
            "expected_holding_window": "Review before candidate expiry.",
            "invalidation_conditions": ["Candidate expires."],
            "missing_evidence": [],
            "source_artifacts": ["ev_supported"],
        },
    }


def _cockpit() -> dict[str, object]:
    return {
        "status": "AVAILABLE",
        "source_paths": {"canonical_operator_state": "/truth/canonical.json", "operator_brief": "/truth/brief.json", "runtime_truth": "/truth/runtime.json"},
        "runtime": {"highest_readiness_layer": "READY", "runtime_truth_classification": "COMPLETE"},
        "opportunities": {"market_data_summary": {"missing_symbols": [], "stale_symbols": []}, "sleeve_run_summary": []},
        "top_candidates": [_supported_candidate()],
        "candidate_decisions_corrections": {},
        "sleeve_warnings": {},
    }


def _cockpit_with_vix_blocker() -> dict[str, object]:
    cockpit = _cockpit()
    cockpit["runtime"] = {"highest_readiness_layer": "READY_PARTIAL", "runtime_truth_classification": "PARTIAL_CONTEXT"}
    cockpit["opportunities"] = {
        "market_data_summary": {"missing_symbols": ["VIX"], "stale_symbols": []},
        "sleeve_run_summary": [
            {
                "sleeve_id": "C2_VOL_INCOME_DEFINED_RISK_V1",
                "run_status": "BLOCKED",
                "blocking_inputs": ["VIX"],
                "canonical_blocker": "SLEEVE_INPUT_REQUIREMENT_BLOCKED",
            }
        ],
    }
    return cockpit


def _cockpit_with_operator_snapshot() -> dict[str, object]:
    cockpit = _cockpit()
    cockpit["top_candidates"] = []
    cockpit["operator_state_snapshot"] = {
        "snapshot_id": "operator-snapshot-amt",
        "manual_capture_candidate": {
            "candidate_available": True,
            "selected_exposure_intent_id": "c2_trend_eq_amt_2026-05-20_v1",
            "symbol": "AMT",
            "sleeve_id": "C2_TREND_EQ_PRIMARY_V1",
            "engine_id": "C2_TREND_EQ_PRIMARY_V1",
            "direction": "LONG",
            "blocker_code": "STALE_MARKET_DATA_BLOCKS_CONVERSION",
            "blocker_message": "AMT market data is stale.",
            "stale_market_data": True,
            "paper_trade_intent_created": False,
        },
        "suppressed_candidate_watchlist": {
            "suppressed_count": 41,
            "suppression_code_counts": {"one_primary_per_regime_bucket_suppressed": 41},
            "competing_selected_candidate_id": "c2_trend_eq_amt_2026-05-20_v1",
            "candidates": [
                {
                    "candidate_id": "c2_cross_asset_trend_qqq_2026-05-20_v1",
                    "symbol": "QQQ",
                    "sleeve_id": "C2_CROSS_ASSET_TREND_V1",
                    "suppression_code": "one_primary_per_regime_bucket_suppressed",
                    "competing_selected_candidate_id": "c2_trend_eq_amt_2026-05-20_v1",
                    "watchlist_only": True,
                }
            ],
        },
    }
    return cockpit



def _cockpit_with_dow_capture_ready_ticket() -> dict[str, object]:
    cockpit = _cockpit()
    cockpit["top_candidates"] = []
    cockpit["operator_state_snapshot"] = {
        "snapshot_id": "operator-snapshot-dow",
        "manual_capture_candidate": {
            "candidate_available": True,
            "selected_exposure_intent_id": "c2_mr_dow_2026-05-20_v1",
            "symbol": "DOW",
            "sleeve_id": "C2_MEAN_REVERSION_EQ_V1",
            "engine_id": "C2_MEAN_REVERSION_EQ_V1",
            "direction": "LONG",
            "current_state": "CAPTURE_READY",
            "lifecycle_state": "CAPTURE_READY",
            "manual_capture_ready": True,
            "paper_submit_ready": False,
            "execution_ready": False,
            "blocker_code": "",
            "paper_trade_intent_created": False,
        },
        "suppressed_candidate_watchlist": {"suppressed_count": 0, "candidates": []},
    }
    return cockpit

def _diagnostic_types(snapshot: dict[str, object]) -> set[str]:
    projection = snapshot.get("system_diagnostics_projection") or {}
    return {str(row.get("diagnostic_type") or "") for row in projection.get("diagnostics", [])}


def _snapshot_without_diagnostics(snapshot: dict[str, object]) -> dict[str, object]:
    mutated = copy.deepcopy(snapshot)
    for key in ("system_diagnostics_projection", "system_diagnostic_projection"):
        projection = dict(mutated.get(key) or {})
        projection["diagnostics"] = []
        projection["critical_count"] = 0
        projection["warning_count"] = 0
        mutated[key] = projection
    return mutated


def test_snapshot_builder_gives_every_projection_the_same_snapshot_id() -> None:
    snapshot = build_operator_state_snapshot_v1(_cockpit_with_vix_blocker())
    expected = snapshot["snapshot_id"]

    for key in [
        "operator_today_projection",
        "passive_health_projection",
        "operator_tasks_projection",
        "system_diagnostics_projection",
        "what_changed_projection",
        "opportunities_projection",
        "eod_outcome_projection",
    ]:
        assert snapshot[key]["snapshot_id"] == expected
        assert snapshot[key]["source_fingerprint"] == snapshot["source_fingerprint"]


def test_health_facts_drive_today_health_and_diagnostics() -> None:
    snapshot = build_operator_state_snapshot_v1(_cockpit_with_vix_blocker())

    assert snapshot["health_facts"]["blocked_sleeves_count"] == 1
    assert snapshot["health_facts"]["data_warnings_count"] == 1
    assert snapshot["operator_today_projection"]["blocked_sleeves_count"] == 1
    assert snapshot["operator_today_projection"]["data_warnings_count"] == 1
    assert any(row["health_id"] == "health:blocked_sleeves" and row["value"] == 1 for row in snapshot["passive_health_projection"]["health"])
    assert {"blocked_sleeve", "missing_market_data", "runtime_truth_unavailable"} <= _diagnostic_types(snapshot)
    assert snapshot["validation_result"]["status"] == "PASS"


def test_validator_rejects_blocked_sleeves_with_empty_diagnostics() -> None:
    snapshot = _snapshot_without_diagnostics(build_operator_state_snapshot_v1(_cockpit_with_vix_blocker()))
    result = validate_operator_state_snapshot_v1(snapshot)

    assert result["status"] == "FAIL"
    assert "blocked_sleeve_requires_diagnostic" in {row["invariant"] for row in result["failed_invariants"]}
    assert "empty_diagnostics_requires_clean_health" in {row["invariant"] for row in result["failed_invariants"]}


def test_validator_rejects_data_warnings_with_empty_diagnostics() -> None:
    snapshot = build_operator_state_snapshot_v1(_cockpit())
    snapshot = _snapshot_without_diagnostics(snapshot)
    snapshot["health_facts"]["data_warnings_count"] = 1
    snapshot["health_facts"]["data_warning_count"] = 1
    result = validate_operator_state_snapshot_v1(snapshot)

    assert result["status"] == "FAIL"
    assert "data_warning_requires_diagnostic" in {row["invariant"] for row in result["failed_invariants"]}


def test_validator_rejects_runtime_truth_unavailable_with_empty_diagnostics() -> None:
    snapshot = build_operator_state_snapshot_v1(_cockpit())
    snapshot = _snapshot_without_diagnostics(snapshot)
    snapshot["health_facts"]["runtime_truth_status"] = "unavailable"
    result = validate_operator_state_snapshot_v1(snapshot)

    assert result["status"] == "FAIL"
    assert "runtime_truth_requires_diagnostic" in {row["invariant"] for row in result["failed_invariants"]}


def test_validator_rejects_advisory_partial_with_activity_and_empty_diagnostics() -> None:
    snapshot = build_operator_state_snapshot_v1(_cockpit())
    snapshot = _snapshot_without_diagnostics(snapshot)
    snapshot["health_facts"]["advisory_status"] = "Partial"
    snapshot["health_facts"]["research_observation_count"] = 1
    result = validate_operator_state_snapshot_v1(snapshot)

    assert result["status"] == "FAIL"
    assert "advisory_incomplete_requires_diagnostic" in {row["invariant"] for row in result["failed_invariants"]}


def test_clean_snapshot_allows_empty_diagnostics() -> None:
    snapshot = build_operator_state_snapshot_v1(_cockpit())
    snapshot = _snapshot_without_diagnostics(snapshot)
    snapshot["health_facts"]["candidate_count"] = 0
    snapshot["health_facts"]["research_observation_count"] = 0
    result = validate_operator_state_snapshot_v1(snapshot)

    assert result["status"] == "PASS"


def test_manual_capture_eligibility_is_unchanged_by_snapshot_builder() -> None:
    direct_projection = active_opportunity_projection_v1(_cockpit())
    snapshot = build_operator_state_snapshot_v1(_cockpit())
    snapshot_projection = snapshot["opportunities_projection"]

    assert direct_projection["candidate_count"] == 1
    assert snapshot_projection["candidate_count"] == direct_projection["candidate_count"]
    assert snapshot_projection["candidates"][0]["manual_capture_eligible"] is True
    assert "RECORD_MANUAL_EXTERNAL_CAPTURE" in snapshot_projection["candidates"][0]["candidate_decision_projection"]["allowed_commands"]
    assert snapshot["broker_execution_allowed"] is False
    assert snapshot["autonomous_execution_allowed"] is False
    assert snapshot["order_routing_allowed"] is False


def test_selected_exposure_and_suppressed_watchlist_flow_from_operator_snapshot() -> None:
    snapshot = build_operator_state_snapshot_v1(_cockpit_with_operator_snapshot())

    active = snapshot["active_opportunity_projection"]
    today = snapshot["operator_today_projection"]

    assert active["candidate_count"] == 0
    assert active["selected_candidate_count"] == 1
    assert active["suppressed_count"] == 41
    assert active["blocked_conversion_count"] == 1
    assert active["manual_capture_candidate"]["symbol"] == "AMT"
    assert active["suppressed_candidate_watchlist"]["candidates"][0]["symbol"] == "QQQ"
    assert today["selected_candidate_count"] == 1
    assert today["suppressed_count"] == 41
    assert today["blocked_conversion_count"] == 1
    assert snapshot["health_facts"]["advisory_status"] == "Partial"
    assert "stale_market_data" in _diagnostic_types(snapshot)


def test_dow_capture_ready_ticket_is_counted_separately_from_sleeve_candidates() -> None:
    snapshot = build_operator_state_snapshot_v1(_cockpit_with_dow_capture_ready_ticket())

    active = snapshot["active_opportunity_projection"]
    today = snapshot["operator_today_projection"]

    assert active["candidate_count"] == 0
    assert active["manual_capture_ticket_count"] == 1
    assert active["manual_capture_candidate"]["symbol"] == "DOW"
    assert active["manual_capture_candidate"]["sleeve_id"] == "C2_MEAN_REVERSION_EQ_V1"
    assert today["candidate_count"] == 0
    assert today["sleeve_candidate_count"] == 0
    assert today["manual_capture_ticket_count"] == 1
    assert today["selected_candidate_count"] == 1
    assert snapshot["broker_execution_allowed"] is False
    assert snapshot["autonomous_execution_allowed"] is False
    assert snapshot["order_routing_allowed"] is False
