from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from ops.aegis.operator_command_v1 import (
    _invalid_task_reclassification_event,
    active_opportunity_projection_v1,
    build_operator_health_facts,
    classify_projection_ownership,
    execute_operator_command_v1,
    operator_command_registry_v1,
    operator_task_projection_v1,
    passive_health_projection_v1,
    read_operator_events_v1,
    replay_operator_events_v1,
    system_diagnostic_projection_v1,
    validate_operator_projection_consistency,
    what_changed_projection_v1,
)


def _candidate() -> dict[str, object]:
    return {
        "candidate_id": "cand-qqq-long",
        "symbol": "QQQ",
        "direction": "LONG",
        "sleeve_id": "C2_CROSS_ASSET_TREND_V1",
    }


def _supported_candidate() -> dict[str, object]:
    return {
        "candidate_id": "cand-spy-long",
        "symbol": "SPY",
        "direction": "LONG",
        "sleeve_id": "C2_CROSS_ASSET_TREND_V1",
        "review_state": "review_required",
        "decision_support_brief": {
            "candidate_id": "cand-spy-long",
            "direct_answer": "Manual capture may be reasonable after review.",
            "trust_classification": "partially_supported",
            "trust_score_label": "Partial support",
            "decision_guidance": "reasonable_for_manual_review",
            "why_triggered": "SPY long was generated by the sleeve trigger.",
            "historical_support": [{"item": "event study", "status": "present"}],
            "weakening_factors": [],
            "sleeve_health_context": {"overall_health": "watch"},
            "expected_holding_window": "Review before candidate expiry.",
            "invalidation_conditions": ["Candidate expires."],
            "missing_evidence": [],
            "source_artifacts": ["ev_supported"],
        },
    }


def _cockpit() -> dict[str, object]:
    return {
        "status": "AVAILABLE",
        "source_paths": {"canonical_operator_state": "/truth/canonical.json", "operator_brief": "/truth/brief.json"},
        "runtime": {"highest_readiness_layer": "ADVISORY_ONLY", "runtime_truth_classification": "PARTIAL_CONTEXT"},
        "opportunities": {"market_data_summary": {"missing_symbols": [], "stale_symbols": []}, "sleeve_run_summary": []},
        "top_candidates": [_candidate()],
        "candidate_decisions_corrections": {},
        "sleeve_warnings": {},
    }


def _cockpit_with_vix_blocker() -> dict[str, object]:
    cockpit = _cockpit()
    cockpit["opportunities"] = {
        "market_data_summary": {"missing_symbols": ["VIX"], "stale_symbols": []},
        "sleeve_run_summary": [
            {
                "sleeve_id": "C2_VOL_INCOME_DEFINED_RISK_V1",
                "run_status": "BLOCKED",
                "blocking_inputs": ["VIX"],
                "canonical_blocker": "SLEEVE_INPUT_REQUIREMENT_BLOCKED",
            }
        ],
    }
    return cockpit


def test_operator_command_registry_forbids_execution_order_and_capital_actions() -> None:
    registry = operator_command_registry_v1()

    for command in ["BUY", "SELL", "EXECUTE", "SUBMIT_ORDER", "ROUTE_ORDER", "ALLOCATE_CAPITAL", "MUTATE_SLEEVE"]:
        assert command in registry["forbidden_commands"]
        assert command not in registry["allowed_commands"]
    assert "RECORD_MANUAL_EXTERNAL_CAPTURE" in registry["allowed_commands"]
    assert registry["broker_execution_allowed"] is False


def test_every_open_task_has_primary_command_and_stable_sort() -> None:
    projection = operator_task_projection_v1(_cockpit())
    open_tasks = [task for task in projection["tasks"] if task["resolution_state"] == "open"]

    assert open_tasks
    assert all(task["primary_command"] for task in open_tasks)
    assert all(task["owner_type"] == "operator" for task in open_tasks)
    assert all(task["ui_resolvable"] is True for task in open_tasks)
    assert all(task["workflow_route"] for task in open_tasks)
    assert all(task["direct_action"] not in {"Review", "Open", "Investigate", "Resolve"} for task in open_tasks)
    assert [task["task_id"] for task in projection["tasks"]] == sorted([task["task_id"] for task in projection["tasks"]])


def test_projection_taxonomy_classifies_runtime_vix_candidate_and_health() -> None:
    assert classify_projection_ownership({"diagnostic_type": "runtime_truth_unavailable", "owner_type": "system"}) == "system_diagnostic"
    assert classify_projection_ownership({"diagnostic_type": "stale_market_data", "owner_type": "system"}) == "system_diagnostic"
    assert classify_projection_ownership({"event_type": "new_candidate_generated", "owner_type": "system"}) == "informational"
    assert classify_projection_ownership({"health_type": "readiness", "owner_type": "system"}) == "passive_health"
    assert classify_projection_ownership({"task_type": "candidate_review", "owner_type": "operator"}) == "operator_actionable"
    assert classify_projection_ownership({"task_type": "manual_capture_available", "owner_type": "operator"}) == "operator_actionable"


def test_runtime_truth_and_vix_blocker_are_diagnostics_not_tasks() -> None:
    cockpit = _cockpit_with_vix_blocker()
    tasks = operator_task_projection_v1(cockpit)["tasks"]
    diagnostics = system_diagnostic_projection_v1(cockpit)["diagnostics"]

    assert all("runtime" not in str(task.get("title", "")).lower() for task in tasks)
    assert all(task.get("task_type") != "blocker_resolution_if_operator_actionable" for task in tasks)
    assert any(row["diagnostic_type"] == "runtime_truth_partial" for row in diagnostics)
    assert any(row["diagnostic_type"] == "missing_market_data" and row["issue"].startswith("VIX") for row in diagnostics)
    assert any(row["diagnostic_type"] == "blocked_sleeve" and row["operator_impact"].find("VIX") >= 0 for row in diagnostics)
    assert all(row["ownership_classification"] == "system_diagnostic" for row in diagnostics)
    vix = next(row for row in diagnostics if row["diagnostic_type"] == "missing_market_data")
    assert vix["required_canonical_symbol"] == "VIX"
    assert vix["symbol_status"] == "missing"
    assert vix["affected_sleeves"] == ["C2_VOL_INCOME_DEFINED_RISK_V1"]
    assert "provider_attempts" in vix


def test_system_diagnostics_include_operator_impact_and_remediation_when_available() -> None:
    diagnostics = system_diagnostic_projection_v1(_cockpit_with_vix_blocker())["diagnostics"]
    vix = next(row for row in diagnostics if row["diagnostic_type"] == "missing_market_data")

    assert vix["operator_impact"]
    assert vix["operator_actionable"] is True
    assert {action["command_id"] for action in vix["remediation_actions"]} >= {"REFRESH_MARKET_DATA", "MARK_PROVIDER_DATA_NEEDED"}
    assert "Review" not in {action["label"] for action in vix["remediation_actions"]}


def test_shared_health_facts_drive_passive_health_and_diagnostics() -> None:
    cockpit = _cockpit_with_vix_blocker()
    facts = build_operator_health_facts(cockpit)
    health = passive_health_projection_v1(cockpit)
    diagnostics = system_diagnostic_projection_v1(cockpit)

    assert facts["blocked_sleeves_count"] == 1
    assert facts["data_warnings_count"] == 1
    assert facts["advisory_status"] == "Partial"
    assert any(row["health_id"] == "health:blocked_sleeves" and row["value"] == 1 for row in health["health"])
    assert any(row["diagnostic_type"] == "blocked_sleeve" for row in diagnostics["diagnostics"])
    assert any(row["diagnostic_type"] == "advisory_projection_incomplete" for row in diagnostics["diagnostics"])


def test_runtime_truth_unavailable_emits_runtime_truth_unavailable_diagnostic() -> None:
    cockpit = _cockpit()
    cockpit["runtime"] = {"runtime_truth_classification": "UNAVAILABLE", "highest_readiness_layer": "ADVISORY_ONLY"}
    diagnostics = system_diagnostic_projection_v1(cockpit)["diagnostics"]

    assert any(row["diagnostic_type"] == "runtime_truth_unavailable" for row in diagnostics)


def test_consistency_validator_catches_mismatch_and_projection_emits_inconsistency() -> None:
    passive = {
        "health": [
            {"health_id": "health:blocked_sleeves", "value": 1, "requires_diagnostic": True},
            {"health_id": "health:stale_data", "value": 0, "requires_diagnostic": False},
            {"health_id": "health:runtime_truth", "value": "available", "requires_diagnostic": False},
            {"health_id": "health:advisory", "value": "Ready", "requires_diagnostic": False},
        ]
    }
    issues = validate_operator_projection_consistency({}, passive, {"diagnostics": []})

    assert any(issue["rule"] == "blocked_sleeves_require_diagnostic" for issue in issues)
    assert any(issue["rule"] == "no_false_no_diagnostics_state" for issue in issues)


def test_projection_inconsistency_diagnostic_shape() -> None:
    passive = {
        "health": [
            {"health_id": "health:blocked_sleeves", "value": 1, "requires_diagnostic": True},
            {"health_id": "health:stale_data", "value": 0, "requires_diagnostic": False},
            {"health_id": "health:runtime_truth", "value": "available", "requires_diagnostic": False},
            {"health_id": "health:advisory", "value": "Ready", "requires_diagnostic": False},
        ]
    }
    issues = validate_operator_projection_consistency({}, passive, {"diagnostics": []})
    assert issues


def test_what_changed_is_informational_only_and_health_has_no_actions() -> None:
    changes = what_changed_projection_v1(_cockpit_with_vix_blocker())["events"]
    health = passive_health_projection_v1(_cockpit_with_vix_blocker())["health"]

    assert changes
    assert all(row["action_required"] is False for row in changes)
    assert all(row["ownership_classification"] == "informational" for row in changes)
    assert all(row["action_required"] is False for row in health)
    assert all(row["ownership_classification"] == "passive_health" for row in health)


def test_invalid_operator_task_reclassification_event_preserves_fingerprint() -> None:
    invalid_task = {
        "task_id": "task:bad",
        "task_type": "runtime_truth_missing",
        "owner_type": "system",
        "created_from_source_hash": "source-hash",
        "primary_command": None,
    }
    event = _invalid_task_reclassification_event(invalid_task, "OWNER_NOT_OPERATOR", "system_diagnostic")

    assert event["event_type"] == "INVALID_OPERATOR_TASK_RECLASSIFIED"
    assert event["rejected_task_type"] == "runtime_truth_missing"
    assert event["original_projection_source"] == "source-hash"
    assert event["new_projection_type"] == "system_diagnostic"
    assert event["projection_fingerprint"]


def test_candidate_decision_projection_is_server_owned() -> None:
    projection = active_opportunity_projection_v1(_cockpit())
    candidate = projection["research_observations"][0]

    assert candidate["candidate_decision_projection"]["candidate_id"] == "cand-qqq-long"
    assert candidate["candidate_decision_projection"]["trust_classification"] == "unsupported"
    assert "projection_fingerprint" in candidate["candidate_decision_projection"]


def test_unsupported_candidate_moves_to_research_observations_without_manual_capture() -> None:
    projection = active_opportunity_projection_v1(_cockpit())

    assert projection["candidates"] == []
    assert projection["candidate_count"] == 0
    assert projection["research_observation_count"] == 1
    observation = projection["research_observations"][0]
    assert observation["symbol"] == "QQQ"
    assert observation["research_observation_reason"] == "Supporting evidence incomplete"
    assert "RECORD_MANUAL_EXTERNAL_CAPTURE" not in observation["candidate_decision_projection"]["allowed_commands"]
    assert set(observation["candidate_decision_projection"]["allowed_commands"]) == {
        "REQUEST_MORE_EVIDENCE",
        "WATCHLIST_CANDIDATE",
        "DISMISS_CANDIDATE",
        "OPEN_EVIDENCE",
    }


def test_supported_candidate_remains_open_opportunity_with_manual_capture() -> None:
    cockpit = _cockpit()
    cockpit["top_candidates"] = [_supported_candidate()]
    projection = active_opportunity_projection_v1(cockpit)

    assert projection["candidate_count"] == 1
    assert projection["research_observation_count"] == 0
    candidate = projection["candidates"][0]
    assert candidate["manual_capture_eligible"] is True
    assert "RECORD_MANUAL_EXTERNAL_CAPTURE" in candidate["candidate_decision_projection"]["allowed_commands"]


def test_forbidden_command_writes_rejected_event(tmp_path: Path) -> None:
    result = execute_operator_command_v1(
        truth_root=tmp_path,
        repo_root=REPO_ROOT,
        day_utc="2026-05-19",
        cockpit_payload=_cockpit(),
        request_payload={"command_type": "BUY", "target_id": "cand-qqq-long", "actor": "David"},
    )

    events = read_operator_events_v1(truth_root=tmp_path, day_utc="2026-05-19")
    assert result["ok"] is False
    assert result["reason"] == "COMMAND_NOT_ALLOWED"
    assert len(events) == 1
    assert events[0]["event_type"] == "OPERATOR_COMMAND_REJECTED"


def test_stale_projection_fingerprint_blocks_sensitive_manual_capture(tmp_path: Path) -> None:
    result = execute_operator_command_v1(
        truth_root=tmp_path,
        repo_root=REPO_ROOT,
        day_utc="2026-05-19",
        cockpit_payload=_cockpit(),
        request_payload={
            "command_type": "RECORD_MANUAL_EXTERNAL_CAPTURE",
            "target_id": "cand-qqq-long",
            "source_projection_fingerprint": "stale",
            "actor": "David",
            "payload": {"quantity": 1, "manually_captured": True, "unsupported_evidence_acknowledgement": True},
        },
    )

    assert result["ok"] is False
    assert result["reason"] == "STALE_PROJECTION_FINGERPRINT"
    assert read_operator_events_v1(truth_root=tmp_path, day_utc="2026-05-19")[0]["event_type"] == "OPERATOR_COMMAND_REJECTED"


def test_manual_capture_snapshots_decision_support_fingerprint(tmp_path: Path) -> None:
    cockpit = _cockpit()
    cockpit["top_candidates"] = [_supported_candidate()]
    decision = active_opportunity_projection_v1(cockpit)["candidates"][0]["candidate_decision_projection"]
    result = execute_operator_command_v1(
        truth_root=tmp_path,
        repo_root=REPO_ROOT,
        day_utc="2026-05-19",
        cockpit_payload=cockpit,
        request_payload={
            "command_type": "RECORD_MANUAL_EXTERNAL_CAPTURE",
            "target_id": "cand-spy-long",
            "source_projection_fingerprint": decision["projection_fingerprint"],
            "actor": "David",
            "payload": {
                "quantity": 1,
                "manually_captured": True,
                "capture_timestamp": "2026-05-19T15:50:00Z",
                "unsupported_evidence_acknowledgement": True,
            },
        },
    )

    events = read_operator_events_v1(truth_root=tmp_path, day_utc="2026-05-19")
    assert result["ok"] is True
    assert len(events) == 1
    assert events[0]["event_type"] == "MANUAL_EXTERNAL_CAPTURE_RECORDED"
    assert events[0]["decision_support_snapshot"]["projection_fingerprint"] == decision["projection_fingerprint"]
    assert events[0]["manual_capture_snapshot"]["decision_support_fingerprint"] == decision["projection_fingerprint"]
    assert events[0]["manual_capture_snapshot"]["symbol"] == "SPY"
    assert events[0]["manual_capture_snapshot"]["quantity"] == 1
    assert events[0]["manual_capture_snapshot"]["acknowledgement_text_accepted"] == "I understand Aegis evidence is incomplete and Aegis did not execute this trade."
    assert events[0]["operator_statement"] == "Aegis did not execute this trade."


def test_replay_rebuild_matches_operator_event_log(tmp_path: Path) -> None:
    execute_operator_command_v1(
        truth_root=tmp_path,
        repo_root=REPO_ROOT,
        day_utc="2026-05-19",
        cockpit_payload=_cockpit(),
        request_payload={
            "command_type": "REQUEST_MORE_EVIDENCE",
            "target_id": "cand-qqq-long",
            "actor": "David",
            "operator_note": "Need linked expectancy.",
        },
    )

    events = read_operator_events_v1(truth_root=tmp_path, day_utc="2026-05-19")
    replay = replay_operator_events_v1(events)
    assert replay["event_count"] == 1
    assert replay["candidate_states"]["cand-qqq-long"]["last_event_type"] == "MORE_EVIDENCE_REQUESTED"
