STATE_DRAFT = "draft"
STATE_PROPOSED = "proposed"
STATE_VALIDATED = "validated"
STATE_APPROVED = "approved"
STATE_SHADOW = "shadow"
STATE_PILOT = "pilot"
STATE_ACTIVE = "active"
STATE_REVIEW_DUE = "review_due"
STATE_DEPRECATED = "deprecated"
STATE_SUPERSEDED = "superseded"
STATE_ARCHIVED = "archived"
STATE_BLOCKED = "blocked"
STATE_ROLLED_BACK = "rolled_back"

ALL_STATES = (
    STATE_DRAFT,
    STATE_PROPOSED,
    STATE_VALIDATED,
    STATE_APPROVED,
    STATE_SHADOW,
    STATE_PILOT,
    STATE_ACTIVE,
    STATE_REVIEW_DUE,
    STATE_DEPRECATED,
    STATE_SUPERSEDED,
    STATE_ARCHIVED,
    STATE_BLOCKED,
    STATE_ROLLED_BACK,
)

ALLOWED_TRANSITIONS = {
    STATE_DRAFT: {STATE_PROPOSED, STATE_ARCHIVED, STATE_BLOCKED},
    STATE_PROPOSED: {STATE_VALIDATED, STATE_BLOCKED, STATE_ARCHIVED},
    STATE_VALIDATED: {STATE_APPROVED, STATE_BLOCKED, STATE_ARCHIVED},
    STATE_APPROVED: {STATE_SHADOW, STATE_PILOT, STATE_ACTIVE, STATE_SUPERSEDED, STATE_BLOCKED},
    STATE_SHADOW: {STATE_PILOT, STATE_ACTIVE, STATE_REVIEW_DUE, STATE_SUPERSEDED, STATE_BLOCKED},
    STATE_PILOT: {STATE_ACTIVE, STATE_REVIEW_DUE, STATE_SUPERSEDED, STATE_BLOCKED},
    STATE_ACTIVE: {STATE_REVIEW_DUE, STATE_DEPRECATED, STATE_SUPERSEDED, STATE_ROLLED_BACK},
    STATE_REVIEW_DUE: {STATE_ACTIVE, STATE_DEPRECATED, STATE_SUPERSEDED, STATE_BLOCKED},
    STATE_DEPRECATED: {STATE_SUPERSEDED, STATE_ARCHIVED},
    STATE_SUPERSEDED: {STATE_ARCHIVED},
    STATE_ARCHIVED: set(),
    STATE_BLOCKED: {STATE_DRAFT, STATE_PROPOSED, STATE_ARCHIVED},
    STATE_ROLLED_BACK: {STATE_ARCHIVED},
}


def validate_state(value: str) -> str:
    if value not in ALL_STATES:
        raise ValueError(f"UNKNOWN_LIFECYCLE_STATE:{value}")
    return value


def validate_transition(current_state: str, next_state: str) -> None:
    validate_state(current_state)
    validate_state(next_state)
    if next_state not in ALLOWED_TRANSITIONS[current_state]:
        raise ValueError(f"ILLEGAL_LIFECYCLE_TRANSITION:{current_state}->{next_state}")
